version: "3"
services:
  app_flask:
    build: ./myapp
    container_name: app_flask
    restart: always
    ports:
      - "5000:5000"
    networks:
      - dock-vv-network

networks:
  dock-vv-network:
    external: true
